# Generated by Django 2.0.1 on 2018-02-01 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_dept', models.CharField(max_length=200)),
                ('project_owner', models.CharField(max_length=100)),
                ('submited_time', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vul_Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Vul_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vulmgmt_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('vul_desc', models.TextField()),
                ('vul_dept', models.CharField(max_length=100)),
                ('vul_responser', models.CharField(max_length=24)),
                ('vul_tracker', models.CharField(max_length=24)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('modified_time', models.DateTimeField()),
                ('closed_time', models.DateTimeField()),
                ('remark', models.CharField(max_length=200)),
                ('vul_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulmgmt.Vul_Level')),
                ('vul_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulmgmt.Vul_Status')),
            ],
        ),
        migrations.AddField(
            model_name='schedule_task',
            name='project_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulmgmt.Vul_Status'),
        ),
    ]
